stages:
  - test
  - publish

eslint:
  stage: test
  image: node:6
  cache:
    paths:
      - node_modules/
  script:
    - npm install --quiet
    - npm run -s eslint
  tags:
    - docker

npm-publish:
  stage: publish
  image: node:6
  script:
    - echo "$NPM_AUTH" >> ~/.npmrc
    - echo "unsafe-perm=true" >> ~/.npmrc
    - npm publish
  only:
    - tags
  tags:
    - docker
